패키지 구조 변경 & Notification
rawfishthelgh/2022_autumn_festival_back pull request #1
Opened 2022-10-14 20:44 UTC by rawfishthelgh

안녕하세요! 첫 사이드 프로젝트 pr을 요청합니다. 패키지 구조를 변경하느라 파일 변경이 많지만, Notification 패키지 코드에 대해서만 코드 리팩토링을 진행해 이 부분 봐주시면 감사하겠습니다!

### 개요
- 전체 프로젝트 패키지 구조를 같은 layer끼리 묶었던 계층형 패키지 구조에서, 도메인 기준으로 묶는 도메인 패키지 구조로 변경했습니다
- Notification 패키지에 대해서만 리팩토링을 진행했습니다

### 리팩토링
1. Notification.java
- setter와 getter의 사용을 지양하기 위해 @Data 어노테이션을 제거했습니다.
- 기존 코드에서는 setter를 통해 공지사항 PUT 요청을 처리했는데, setter를 사용하지 않기 위해 updateNotification이라는 메소드를 엔티티 내부에 만들어 service에서 이를 호출할 수 있도록 구성해봤습니다
- 생성자 부분 코드를 줄이기 위해 @AllArgsConstructor 어노테이션을 추가했습니다

2. NotificationRequestDto.java, NotificationResponseDto.java
- 역시 setter의 사용을 지양하기 위해 @Data 어노테이션을 @Getter로 어노테이션을 변경했습니다.
- 마찬가지로 생성자 부분 코드를 줄이기 위해 @AllArgsConstructor 어노테이션을 추가했습니다.
- 원래 하나의 DTO에서 요청과 응답을 모두 처리했지만, 요청과 응답 DTO 클래스를 구분했습니다.
- 요청 DTO에서는 dto를 엔티티로 변환하는 toEntity(), 응답 DTO에서는 엔티티를 DTO로 변환하는 toDto() 함수를 public으로 선언하여 서비스 계층에서 활용할 수 있도록 했습니다.

3. NotificationService.java
- 불필요하게 중복되는 코드를 최대한 줄이기 위해 노력해봤습니다. 가령 NotificationDto에서 Notification으로, 혹은 Notification에서 NotificationDto로 빌더 패턴을 통해 변환하는 부분을 DTO에 toEntity(), toDto() 메소드를 생성해 중복되는 부분을 대체했습니다
- 또 기존의 createNotification 메소드에서 객체복사(BeanUtils.copyProperties)를 통해 DTO에서 Entity로 변환하던 부분 또한 toEntity() 메소드를 통해 처리하도록 변경했습니다
- 기존 updateNotification 메소드에서는 setter를 통해 기존 객체의 상태를 변경시켰는데, 이제는 객체의 메소드를 활용해 값을 새로 생성하도록 했습니다
- 기존 readNotification 로직에서 isEmpty()를 통해 null 값 체크를 하던 부분의 코드를 경량화하기 위해, orElseThrow()를 이용해 예외를 발생시키도록 변경했습니다.

### 다음

- 현재는 공지사항 생성 요청을 할 때 이미지와 json을 한 요청에서 받아 처리하도록 설계했는데, 이미지 업로드를 담당하는 api를 따로 생성해 이미지 업로드는 다른 요청에서 수행하도록 할 예정입니다
- 코드 가독성을 위해 서비스 계츠에서 for문이 아닌 스트림을 사용할 예정입니다.
- Booth 패키지에 대한 리팩토링을 진행할 예정입니다

2022-10-18 07:10 UTC, boorownie requested changes
안녕하세요! 리뷰를 진행한 류성현입니다.
리뷰할 포인트를 명확히 전달해주셔서 수월하게 리뷰를 할 수 있었습니다.
말씀 주신대로 변경된 파일은 많지만 리뷰할 부분이 많지 않아 코멘트 드릴 부분이 많이 없긴했지만
몇가지 코멘트 남겼으니 참고해주세요~

2022-10-18 07:10 UTC, boorownie commented on festival/src/main/java/likelion/festival/notification/converter/NotificationStringToRequestDtoConverter.java
> +public class NotificationStringToRequestDtoConverter extends Throwable implements
혹시 해당 클래스는 어디서 사용하나요?

2022-10-18 07:10 UTC, boorownie commented on festival/src/main/java/likelion/festival/notification/controller/NotificationController.java
> +    return "Ok";
사소한 부분일 순 있지만 [rfc 문서](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.5)에 의하면 DELETE 요청에 body가 없는 경우 200 보다는 204가 더 적합할 수 있습니다.

2022-10-18 07:10 UTC, boorownie commented on festival/src/main/java/likelion/festival/notification/dto/NotificationRequestDto.java
> +  public Notification toEntity(NotificationRequestDto notificationRequestDto) {
인자가 필요한가요?

```suggestion
  public Notification toEntity() {
```

2022-10-18 07:10 UTC, boorownie commented on festival/src/main/java/likelion/festival/notification/service/NotificationService.java
> +        notificationRequestDto.getImages());
Notificaion의 상태(변수)가 변경될 때 마다 해당 부분에 대한 코드 수정이 필요해보이는데요~
Notificaion의 변경에 영향을 받지 않도록 코드를 구현하면 어떨까요?

```suggestion
    Notification newNotification = notificationRequestDto.toEntity();
    notification.updateNotification(newNotification);
```

2022-10-18 07:10 UTC, boorownie commented on festival/src/main/java/likelion/festival/notification/service/NotificationService.java
> +      return notificationResponseDtos;
스트림을 이용하는 것도 방법이겠네요~
```suggestion
      return notificationRepository.findAll().streams()
          .map(it -> NotificationResponseDto.toDto(it))
          .collect(Collectors.toList());
```

2022-10-18 07:10 UTC, boorownie commented on festival/src/main/java/likelion/festival/notification/service/NotificationService.java
> +  public List<NotificationResponseDto> readNotificationAll(NotificationType notificationType) {
해당 메서드에서는 Notification 목록을 조회하는 로직과 DTO로 변환하는 로직이 있는데요
type의 유무에 따라 Notification 목록을 조회하는 로직이 분기되어 처리되고 있네요!
Notification 목록을 조회하는 로직을 메서드로 분리하면 어떨까요?

2022-10-21 16:15 UTC, rawfishthelgh commented on festival/src/main/java/likelion/festival/notification/converter/NotificationStringToRequestDtoConverter.java
> +public class NotificationStringToRequestDtoConverter extends Throwable implements
본래 createNotification 요청을 할 때, 하나의 요청에서 notification 생성 요청과 더불어 이미지 생성 요청까지 수행했습니다. form-data 형식으로 file과 json string을 한꺼번에 보낼 때 json string을 dto로 바인딩하기 위해 converter를 사용했습니다! 하지만 이제 이미지를 업로드하는 api는 별개로 분리하여 사용할 예정이므로 이 클래스는 삭제했습니다.
- [참고한 레퍼런스](https://hello-bryan.tistory.com/347)

2022-10-21 16:31 UTC, rawfishthelgh commented
안녕하세요! 주신 코드 리뷰 바탕으로 코드를 수정해봤습니다. 확실히 코드가 깔끔해진 것 같아 기분이 좋네요ㅎㅎ 놓친 부분이 있다면 지적해주시면 감사하겠습니다! 이후 다른 패키지의 리팩토링을 진행해보려 합니다.

### 피드백 반영 내용
***
- delete 요청 시 http 응답을 204로 지정했습니다
- NotificationRequestDto의 toEntity() 메소드를 파라미터 없이 쓸 수 있도록 수정했습니다
- Notification의 updateNotification 메소드를 서비스 로직에서 notification 객체만 던지면 객체 내부에서 알아서 수정을 수행하도록 해봤습니다.
- NotificationService에서 for 문을 사용하는 부분을 전부 스트림을 활용해서 수정했습니다. 개인적으로 이 부분 정말 시원하네요ㅎㅎ
-  NotificationService에서 notification을 조회하는 메소드를 분리해봤습니다! 한 메소드에서 하나의 역할을 하게 됐네요ㅎㅎ

2022-10-21 16:34 UTC, rawfishthelgh commented on festival/src/main/java/likelion/festival/notification/entity/Notification.java
> +        .modifiedDateTime(getModifiedDateTime())
이 부분에서 질문이 있는데요! baseEntity의 값을 참조하기위해 getter를 사용하긴 했는데...이런 경우 Getter를 사용하지 않고 값을 가져올 방법이 있을까요??

2022-10-21 16:38 UTC, rawfishthelgh commented on festival/src/main/java/likelion/festival/notification/entity/Notification.java
> +  }
이전 피드백에서 변수의 변경이 일어나면 Service layer에 있는 메소드의 수정이 불가피하다고 말씀해주셨는데요! 이 메소드 역시 변수가 변경될 때 수정을 해야 할 텐데, 같은 클래스 내에서는 이런 부분을 고려하지 않아도 괜찮을까요?

2022-10-22 15:34 UTC, boorownie approved these changes
반영된 부분 확인 + 질문 주신 부분 코멘트 작성 하였습니다.
상당히 많은 코드량의 pr이였지만 파악하는데 문제는 없었어요!
이어서 다음 pr도 기대하고 있겠습니다 :)

2022-10-22 15:34 UTC, boorownie commented on festival/src/main/java/likelion/festival/notification/entity/Notification.java
> +        .modifiedDateTime(getModifiedDateTime())
분명 여러 선택지가 있을 것 같은데요.
만약 그렇다면 private 을 제거하는 것도 방법일 것 같아요!

게터냐 private을 제거하느냐에 대해서 두 방법 다 불편함을 느낄 수 있을거라 생각이 드는데요
우선 우리가 불편함을 느끼는 이유가 무엇이고 진정 불편함을 느끼는게 맞는지에 대해서도 함께 고민해보시면 좋겠어요!

2022-10-22 15:34 UTC, boorownie commented on festival/src/main/java/likelion/festival/notification/entity/Notification.java
> +  }
의존을 하는 경우 변경에 대한 영향을 안 받을 순 없습니다. 그래서 불필요한 의존은 제거하는게 좋죠.
하지만 제거할 수 없는 의존, 그러니까 필요한 의존이라면 변경에 대한 영향을 최소화 하는 방향으로 고민하는 것을 추천합니다.

이 케이스도 인자 타입이 객체인지, 값들을 각각 보내는지에 따라
서비스도 변경에 대해 영향을 받는지, 그렇지 않은지가 결정되는 것 이오니 이점 참고해주세요!

2022-10-23 10:06 UTC, merged